controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

# Main page
root:
    path: /
    controller: App\Controller\HomeController::index      
